# Generated by Django 3.2 on 2021-04-17 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_store'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductCategory',
        ),
    ]
